name: Integração dos testes

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
  
  execucao_terminal:
    runs-on: ubuntu-latest
    needs: [inspection]  
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: executando os testes via terminal
        run: npm run terminal

  relatorio:
    runs-on: ubuntu-latest
    needs: [execucao_terminal]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: executando os testes via terminal
        run: npm run terminal

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: cypress/reports/html